// <auto-generated />
namespace Phase13.Web.DataContexts.RMFSystemMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSAP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSAP));
        
        string IMigrationMetadata.Id
        {
            get { return "201612181219291_AddSAP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
