// <auto-generated />
namespace Phase13.Web.DataContexts.RMFSystemMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPOAM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPOAM));
        
        string IMigrationMetadata.Id
        {
            get { return "201612181432350_AddPOAM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
